---

- name: get join command
  become_user: root
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  become_user: root
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
